version: "2"
services:
  elasticsearch:
    image: elasticsearch:2.3.3
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: kibana:4.5.1
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
  logstash:
    image: logstash:2.3.2
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
  filebeat:
    image: prima/filebeat
    volumes:
      - ./filebeat/filebeat.yml:/filebeat.yml
      - ./log:/var/log
    depends_on:
      - logstash
